### PR TITLE
Use `allow` as better terminology

### PR DESCRIPTION
**Pull request by jamietanna**

### CODE REVIEW

**Review by carolgilabert — APPROVED** [review]

**Review by carolgilabert — CHANGES_REQUESTED** [review]
allowlist here sounds a bit weird, can we try just allow?

**Review by carolgilabert — APPROVED** [review]
Awesome, thanks for the PR! 🙌🏼

**Comment by henryrowett** [comment]
@carolgilabert @jamietanna this PR hasn't been deployed to the API docs - are you happy for me to do that?

**Comment by jamietanna** [comment]
Yes please 🙏

**Pull request merged**
