### PR TITLE
OBIE v3.1.5 Upgrade

### PR DESCRIPTION
**Pull request by henryrowett**
**OBIE v3.1.5 Upgrade**

- `Debtor/Name`
- `TransactionMutability`

### CODE REVIEW

**Review by dukky — COMMENTED** [review]
For the amount of effort we put into the `Debtor/Name` change we don't actually mention this here apart from in a response example, is that intentional?

**Comment by henryrowett** [comment]
what would you expect to see? I can include a section on `Debtor/Name` if we think it will be useful? 

It could be useful to mention that any consent and/or payment order created before we upgrade to v3.1.5 won't contain this data.

**Comment by dukky** [comment]
> what would you expect to see? I can include a section on `Debtor/Name` if we think it will be useful?
> 
> It could be useful to mention that any consent and/or payment order created before we upgrade to v3.1.5 won't contain this data.

Yeah about which consents/payments will contain it, as that's specific to our API/implementation. I think linking to the spec is fine for the rest though, as there's not much point just repeating when/where/why the fields will be present

**Comment by henryrowett** [comment]
cool, I'll include that 👍

**Review by albertmonzo — APPROVED** [review]

**Pull request merged**
