### PR TITLE
expanded the readme

### PR DESCRIPTION
**Pull request by petr-tik**
Including instructions on how to set up slate dev environment, make changes and send PRs

### CODE REVIEW

**Comment by petr-tik** [comment]
@jnic Do you want to close accept or reject and close this?

**Comment by mattheath** [comment]
Hey @petr-tik, thanks for helping out! Could you amend this to just add the _Prerequisites_ section and leave the other text unchanged? Then happy to merge.

**Comment by petr-tik** [comment]
just 
## Prerequisites 
or 
## setting up 
too?

**Comment by billinghamj** [comment]
@petr-tik Include both of those, but don't change the other lines

**Comment by petr-tik** [comment]
Now?

**Comment by albertmonzo** [comment]
6 years stale

**Pull request closed without merging**
